#!/bin/bash
# $Id: mailto,v 1.4 2014/05/19 10:21:02 fulford Exp $
# $Source: /src/merlin/usr/local/etc/RCS/mailto,v $
# $Revision: 1.4 $
# Author C W Fulford.
# Copyright 2014 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0709 229 5385
########################################################################
cmd=`basename $0`
echo $@
syntax="$cmd [-d] [-v]"
while [ $# -gt 0 ] ;do
	case $1 in 
		-d) debug=:;set -x;shift;;
		-v) verbose=0;shift;;
		*)params="$@";shift;continue;;
	esac
done
/usr/bin/terminal -e "/usr/bin/mutt $params"
